name: PerchShulkers
version: '1.1-fixbrokenshulkers'
main: me.entity303.openshulker.OpenShulker
api-version: 1.14
authors: [KayaLambrex]

commands:
  openshulker:
    permission: openshulker.admin
    description: Main command for PerchShulkers admin functions.
  cleanshulkers:
    permission: openshulker.cleanshulkers
    description: Cleans all shulker boxes in your inventory, armor, offhand, and ender chest, or for another player.
    usage: /cleanshulkers [player]

permissions:
  openshulker.admin:
    description: Allows use of /openshulker admin command.
    default: op
  openshulker.cleanshulkers:
    description: Allows use of /cleanshulkers on yourself.
    default: op
  openshulker.cleanshulkers.others:
    description: Allows use of /cleanshulkers <player> on others.
    default: op